### ISSUE TITLE
re-add command aliases from original BuildersUtilities plugin

### ISSUE THREAD

**Issue by NoltoxGit** [TehBrian/BuildersUtilities#59]
Hello !
I like this BU fork made orignally by Arcaniax but before using it on my creative I would like to know if you can add the aliases that BU proposes please. That is to say the following ones :
- /c
- /con
- /convex
- /cub
- /cuboid
- /derot
- /f
- /flip
- /pa
- /r
- /s
- /scale
- /twist

Thanking you for your work ♥
~ Noltox ~

**Comment by TehBrian** [comment]
Yeah, sure! 

The reason that I originally removed them was because:
1. I didn’t want to have a hard dependency on WorldEdit, meaning I didn’t want to require server owners to install WorldEdit to use BuildersUtilities.
2. I didn’t use them myself, and initially, this fork was just for my personal use.
The second reason no longer is applicable, and as for the first reason, we can just make WorldEdit a soft dependency and only enable the aliases if WorldEdit is detected.

So, all that to say, yeah, I’ll add these when I next have the time. Shouldn’t take too long. :-)

**Comment by RedstoneFuture** [comment]
I will explicitly disable that if it comes in BuilderUtilities. For something like this, you should use an alias plugin that also integrates tab completion into the aliases.

**Comment by TehBrian** [comment]
I'll make the aliases configurable with a config setting and disable it by default. So, server owners will be able to opt in to this feature if they want to.

I agree with you that plugin-specific aliases don't necessarily belong in a building utility plugin. However, since the original BuildersUtilities has these aliases and this fork is meant to be a drop-in replacement that enhances existing functionality, we should carry over pre-existing functionality to ensure that server owners don't lose functionality if they switch from the original BuildersUtilities to this fork.

**Comment by RedstoneFuture** [comment]
Okay, I understand.

**Comment by RedstoneFuture** [comment]
**Only these commands are WorldEdit command aliases in the original BU:** ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/system/CommandForwarder.java#L65-L73))
- `/p1` & `/1` _("/1" is already implemented in FAWE)_ -> `/pos1` ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/PosOneAliasCommand.java#L37))
- `/p2` & `/2` _("/2" is already implemented in FAWE)_ -> `/pos2` ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/PosTwoAliasCommand.java#L37))
- `/cuboid` & `/cub` ->`/sel cuboid` ([plugin.yml](https://github.com/Arcaniax-Development/Builders-Utilities/blob/4521e38e38c5de5763173965be389e95cdfab047/src/main/resources/plugin.yml#L56-L59); [Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/CuboidSelectionAliasCommand.java#L37))
- `convex` & `/con` -> `/sel convex` ([plugin.yml](https://github.com/Arcaniax-Development/Builders-Utilities/blob/4521e38e38c5de5763173965be389e95cdfab047/src/main/resources/plugin.yml#L63-L66); [Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/ConvexSelectionAliasCommand.java#L37))
- `/s` -> `/set` ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/SetAliasCommand.java#L44))
- `/r` -> `/replace` ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/ReplaceAliasCommand.java#L44))
- `/pa` _(already implemented in FAWE)_ -> `/paste` ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/PasteAliasCommand.java#L44))
- `/f` -> `/flip` ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/FlipAliasCommand.java#L44))
- `/c` -> `/copy` ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/CopyAliasCommand.java#L44))

---

**Simplified (new) WorldEdit commands in the original BU:**
- `//scale [size] Simplified` deform scaling command ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/ScaleAliasCommand.java))
- `//derot [axis] [degrees]` Simplified deform rotate command ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/DeformRotateAliasCommand.java))
- `//twist [axis] [degrees]` Simplified deform twist command​ ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/aliases/TwistAliasCommand.java))

**Misc aliasses in the original BU:** ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/dcbe831be5158cd549d611ad8d80b1d55117c0ba/src/main/java/net/arcaniax/buildersutilities/commands/system/CommandForwarder.java#L77-L78))
- `walkspeed` & `ws` -> `speed walk` ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/f603b43152207f34738f7502c7ed43197daf6d07/src/main/java/net/arcaniax/buildersutilities/commands/aliases/WalkSpeedAliasCommand.java#L44))
- `flyspeed` & `fs` -> `speed fly` ([Source Code](https://github.com/Arcaniax-Development/Builders-Utilities/blob/f603b43152207f34738f7502c7ed43197daf6d07/src/main/java/net/arcaniax/buildersutilities/commands/aliases/FlySpeedAliasCommand.java#L44))

**Comment by TehBrian** [comment]
Thanks for the info compilation! That'll be helpful.

**Comment by TehBrian** [comment]
Heya @NoltoxGit, I've rewritten the aliases from the original plugin (except for `/ws` and `/fs`), and I *think* they should satisfy your needs. But, please do take a look at https://github.com/TehBrian/BuildersUtilities/commit/f8d9de0ba9587b80f3be52d052402cd464c2ebef and let me know what you think. Also, if you would like a build (i.e., a plugin jar) to test, let me know.
