### ISSUE TITLE
use a GUI framework

### ISSUE THREAD

**Issue by TehBrian** [TehBrian/BuildersUtilities#6]
[Incendo/interfaces](https://github.com/Incendo/interfaces) seems like a good choice, but there might be others that are better-suited for what we're doing in our GUIs.

**Comment by RedstoneFuture** [comment]
Maybe you like this: https://github.com/Phoenix616/InventoryGui

**Comment by TehBrian** [comment]
At least for right now, I don't think there's much benefit to refactoring the plugin to use a GUI framework. We're not currently planning on adding any new GUIs, and our current setup is accomplishing everything we need it to do. It'd make the code prettier, sure, but squashing our current code into a framework would offer less flexibility overall and would consume developer time that could be better spent elsewhere (like adding new features that players could actually see and use).

Closing as unplanned for now. Maybe in the future if we need better GUI abstractions for more advanced GUIs we can reopen this issue.
