### ISSUE TITLE
update to 1.21

### ISSUE THREAD

**Issue by LMRaceTeam** [TehBrian/BuildersUtilities#66]
I really need this mod for 1.21 but as of now its only 1.20.4 and seems to be discontinued as that was january it is now july/ nearly august. please update this mod to fabric 1.21 as fast as possible, thank you very much.

**Comment by TehBrian** [comment]
I'm working on updating the mod to 1.20.6/1.21, and a release will be available soon.

Also, please note that this mod is not compatible with a Fabric server. It's only available for Paper servers.

**Comment by LMRaceTeam** [comment]
ok thanks, does this mod work on single players aswell or does it have to be a server?

**Comment by Loapu** [comment]
This mod (technically called a "plugin") is server side only, as it is written for [Paper](https://papermc.io)

**Comment by TehBrian** [comment]
Done! :D https://modrinth.com/plugin/buildersutilities/version/1.8.2
